### ISSUE TITLE
topics的问题

### ISSUE THREAD

**Issue by wwh-maker** [thinkphp5-inaction/bbs#2]
请问主题里有六个贴子了，但是帖子确没有显示出来是为什么；
每次发了帖子跳转的时候却显示主题不存在，但是存到数据库里去了

**Comment by xialeistudio** [comment]
看一下执行的SQL语句

**Comment by wwh-maker** [comment]
SELECT * FROM `bbs_topic` WHERE ( `forum_id` = 1 ) AND `bbs_topic`.`deleted_at` IS NULL ORDER BY `top` DESC,`topic_id` DESC LIMIT 0,10 [ RunTime:0.000445s ]

我发现原因是这个:`bbs_topic`.`deleted_at` IS NULL应该是`bbs_topic`.`deleted_at` = 0 ，解决了

**Comment by wwh-maker** [comment]
解决了
